- id: check-coverage
  name: Check Coverage
  # check command. 容器名 容器内manage.py 覆盖率
  entry: .pre-commit-hooks/check_coverage.sh [container_name] [manage.py] [90]
  language: script
  stages: [commit]

# - id: generate-sample-file
#   name: generate sample file
#   # check command. 配置文件名 配置文件类型
#   entry: .pre-commit-hooks/generate_sample_file.sh [config_file_name] [config_file_type]
#   language: script
#   stages: [commit]

- id: generate-sample-toml-file
  name: 生成toml配置文件
  description: python处理
  entry: generate_sample_toml
  language: python

- id: generate-sample-env-file
  name: 生成env配置文件
  description: node处理
  entry: generate_sample_env
  language: node